
/**
 @file 
   AUTOGENERATED Thermistor table
   
   Rth          = 100.00k
   B            = 3950
   Rload        = 100.00k
   Inverted     = False
   ADC bits     = 10
   Table bits   = 5
   Temp Scaled  = x100
 */        
#include "InterpolatedLookup.h"
 
class TempTable100kB3950x100 : public InterpolatedLookup1DBits<int16_t, float, 10, 5>
{
    typedef InterpolatedLookup1DBits<int16_t,float, 10, 5> Base;
    
    static const int16_t _table[];
    
public:
    TempTable100kB3950x100() : Base(_table, 100)
    {}
    
    static TempTable100kB3950x100 _instance;
    
};



